apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: broker-ingress-hpa
  namespace: cloud-run-events
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: broker-ingress
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 450Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: broker-fanout-hpa
  namespace: cloud-run-events
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: broker-fanout
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 900Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: broker-retry-hpa
  namespace: cloud-run-events
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: broker-retry
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 1400Mi